spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog
      username: root
      password: 121121
    mvc:
        view:
          prefix: /template/
          suffix: .html
    thymeleaf:
      cache: false
      content-type: text/html
      charset:
      encoding: UTF-8
      mode: HTML5
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    http:
      multipart:
        max-request-size: 10Mb
        enabled: true
        max-file-size: 10Mb
server:
  port: 8888
  session:
    cookie:
      name: vissun
  tomcat:
    max-http-post-size: 102400

resource:
  path: E:\\WebPackage\\IdeaProjects\\BackEnd_vissun\\src\\main\\resources\\static\\